### ISSUE TITLE
Usage instructions missing from repository

### ISSUE THREAD

**Issue by tailorvj** [HaarigerHarald/omxiv#10]
Thanks for building this solution. It seems so promising as a frame server for the Pi. Could you please provide info about the protocol used by the program and how to interface with it from the command line and from SSH?

Kind regards,
Tailor

**Comment by Ruffio** [comment]
Protocols? How to use omxiv is documented here: https://github.com/HaarigerHarald/omxiv#synopsis

This should be closed
