### ISSUE TITLE
error: ‘OMX_DISPLAY_ALPHA_FLAGS_MIX’ undeclared

### ISSUE THREAD

**Issue by Jroom2672** [HaarigerHarald/omxiv#14]
Hello,

I have a problem with make command : 

`pi@raspberrypi:~ $ cd omxiv

pi@raspberrypi:~/omxiv $ make ilclient
mkdir -p libs
cp -ru /opt/vc/src/hello_pi/libs/ilclient libs
make -C libs/ilclient
make[1] : on entre dans le répertoire « /home/pi/omxiv/libs/ilclient »
make[1]: rien à faire pour « all ».
make[1] : on quitte le répertoire « /home/pi/omxiv/libs/ilclient »

pi@raspberrypi:~/omxiv $ make
cc -DVERSION=\"2f27c1d4a6\" -DLCURL_NAME=\"libcurl.so.4\" -O3 -fdata-sections -ffunction-sections -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -Wall -pipe -DHAVE_LIBOPENMAX=2 -DOMX -DOMX_SKIP64BIT -ftree-vectorize -DUSE_EXTERNAL_OMX -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM -Wno-psabi -I./libnsbmp -I./libnsgif -I./libs/ilclient -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -g -c omx_render.c -o omx_render.o -Wno-deprecated-declarations
omx_render.c: In function ‘setOmxDisplayConfig’:
omx_render.c:309:21: error: ‘OMX_DISPLAY_ALPHA_FLAGS_MIX’ undeclared (first use in this function)
   dispConfRT.alpha|=OMX_DISPLAY_ALPHA_FLAGS_MIX;
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
omx_render.c:309:21: note: each undeclared identifier is reported only once for each function it appears in
Makefile.include:11 : la recette pour la cible « omx_render.o » a échouée
make: *** [omx_render.o] Erreur 1
`
No answer on google, so I'm heading to you to solve this problem.

Thank you, Jérôme.

**Comment by HaarigerHarald** [comment]
Duplicate #12
