### ISSUE TITLE
Open command after viewing

### ISSUE THREAD

**Issue by marrobHD** [HaarigerHarald/omxiv#15]
Please add a feature by using a parameter, e.g. -command "chromium-browser" after closing the image a certain command is executed. Thanks

**Comment by HaarigerHarald** [comment]
A standard "omxiv ... && chromium-browser ... " does not work?

**Comment by marrobHD** [comment]
No I have raspicast installed. There is no source code available for the apk. There is only an option for omxiv command line Options https://imgur.com/bEC0tVN

**Comment by ffloress** [comment]
then you should send a pull request to raspicast

**Comment by Ruffio** [comment]
This 'issue' should be closed
