### ISSUE TITLE
Videos not playing

### ISSUE THREAD

**Issue by herna54** [HaarigerHarald/omxiv#16]
I'm using a pi 3 and casting images works fine but casting videos leads to a Black screen and then closes the screen. Do I need to install something else?

**Comment by Ruffio** [comment]
You do know this is an image viewer, right?

![image](https://user-images.githubusercontent.com/1877612/52182956-800f2580-2803-11e9-9f92-0f488ae25185.png)

In order to play video you need a video player...

**Comment by herna54** [comment]
Yes I do have it. Code I did was
'sudo apt-get install omxplayer'

**Comment by matteoraggi** [comment]
yes, to play videos from cli, I suggest you this app wth a similar name: https://github.com/popcornmix/omxplayer

**Comment by FerretDave** [comment]
The instructions for 'raspicast' refer to using both OMXiv and OMXplayer, easy mistake to make

**Comment by Ruffio** [comment]
Please close this issue

**Comment by laddu38732** [comment]
The answer to all questions

$ sudo apt-get install libjpeg8-dev libpng12-dev
$ git clone https://github.com/HaarigerHarald/omxiv
$ cd omxiv
$ make ilclient
$ make -j4
$ sudo make install

And enjoy|||||||

**Comment by kkboy20** [comment]
Raspicast app does not work for youtube anymore
