### ISSUE TITLE
libjpeg8-dev unavailable but required?

### ISSUE THREAD

**Issue by DerRheingold** [HaarigerHarald/omxiv#2]
Hi,
awesome project! Just what I was looking for :)
However, when trying to install libjpeg8-dev I get this message on my Raspi running Kodi/OSMC: 

"Package libjpeg8-dev is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source However the following packages replace it: libjpeg62-turbo-dev
E: Package 'libjpeg8-dev' has no installation candidate"

If I install the version libjpeg62-turbo-dev and try to run "make ilclient" I get further error messages:
"mkdir -p libs
cp -ru /opt/vc/src/hello_pi/libs/ilclient libs cp: cannot stat '/opt/vc/src/hello_pi/libs/ilclient': No such file or directory
Makefile:16: recipe for target 'ilclient' failed
make: * [ilclient] Error 1"

Any idea how to fix/circumvent this?﻿

Cheers :)

**Comment by nagualcode** [comment]
probably your system does not have the raspberry fimware files and libs:
/opt/vc/src/hello_pi/
You my copy it from the official raspberry firmware repo in github,
I suggest you to use raspbian image if you want to play with programming yourself.

**Comment by DerRheingold** [comment]
Hi,

thanks for the quick reply :)
In fact I don't intend to program on my raspberry "just" make some small modifications, like getting it to run as chromecast ;)

So I copied the /opt/vc/src/hello_pi/ from the raspberry firmware to my raspberry and made some progress. Now I get another error message
" fatal error: interface/vcos/vcos.h: No such file or directory
 #include "interface/vcos/vcos.h" "
However in the firmware vcos is located in "opt\vc\include\interface\vcos" having copied the files to that location won't fix the problem. 

Any ideas?

**Comment by HaarigerHarald** [comment]
I'd try to update the firmware with rpi-update. Afaik this overwrites the opt folder with the needed files and file structure, in case that's the problem. 

Moreover I'm pretty sure you can also use other versions of libjpeg.

**Comment by Ruffio** [comment]
@DerRheingold can this issue be closed?

**Comment by Ruffio** [comment]
@DerRheingold can this issue be closed?

**Comment by DerRheingold** [comment]
Sorry, I think you can close it. I found another way to solve my initial problem... but truth be told, I don't remember it anymore ^^

**Comment by Ruffio** [comment]
@DerRheingold can you close this?
