### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Ruffio** [HaarigerHarald/omxiv#32]
Looks like questions keeps coming in but no one answers :-(

**Comment by nagualcode** [comment]
questions like "I cant build on my debian pi" are not project related.

**Comment by Ruffio** [comment]
Fair enough to close howto questions, but do close them. Stackoverflow etc. should be used for that. Multiple errors have been reported without any feedback. A PR is still awating review and possible merge/rejection.

But without any actions at all, it looks dead :-(

**Comment by HaarigerHarald** [comment]
Fair point, but unfortunately I don't have the time and due to network issues in my new appartment it is hard for me to test stuff. If someone wants to take over maintanace I'd be glad.
