### ISSUE TITLE
encountering this error...

### ISSUE THREAD

**Issue by Shabinder** [HaarigerHarald/omxiv#34]
assertion failure:ilclient.c:747:ilclient_change_component_state():error == OMX_ErrorNone

Any help will be appreciated.

**Comment by kenohassler** [comment]
I encountered the same error.

### Short answer
In my case, the amount of memory for the video core was not enough. I bumped it from 64MiB to 128MiB:
```
sudo raspi-config
```
Navigate to Performance > GPU memory. Increase the value, click finish and reboot the Pi. Now it should work 👍

### Longer answer
Sadly, the error messages are not very useful. Using a debugger, you can extract helpful information though:
```
make clean
make debug
gdb ./omxiv
```
Then, in gdb, set a breakpoint and run omxiv on the file that gave the error:
```
b ilclient.c:747
r <path-to-file>
```
Every time you hit the breakpoint, enter `p error`. If it is `OMX_ErrorNone`, type `c` and check the next one.
That way, you should find the exact error. Mine was `OMX_ErrorInsufficientResources`.

Credits for this go to [https://jan.newmarch.name/LinuxSound/Diversions/RaspberryPiOpenMAX/](https://jan.newmarch.name/LinuxSound/Diversions/RaspberryPiOpenMAX/), section 17.6: ilclient errors.


_Note: you should really give your github issues a more descriptive name!_
