### ISSUE TITLE
Trying to clone image

### ISSUE THREAD

**Issue by eddie-46** [HaarigerHarald/omxiv#39]
hello im new to this so this might be a simple issue im having but i was trying to get a clone for my raspberry-pi but when i enter the command "git clone https://github.com/HaarigerHarald/omxiv" i just this message "-bash: git: command not found" im,using putty to connect to the pi idk if thats whats causing the issue. Is there a way to install it with a usb or file share it over wifi any suggestions help thank you

**Comment by nagualcode** [comment]
you need to instal git package on you raspberry pi.
if you are using a debian based distro, that would be like:
```
apt install git
```

**Comment by eddie-46** [comment]
Thank you that worked. I appreciate the help!
