### ISSUE TITLE
Unable to cast after setup- No errors

### ISSUE THREAD

**Issue by dilipprasad** [HaarigerHarald/omxiv#4]
Hi, 
Even after setting up, i am not receiving any errors. Kindly help here.

How to start manually? Phone says the video is being casted from my phone, but unable to see in the screen.

**Comment by Ruffio** [comment]
Did you find out how to resolve this?

**Comment by Ruffio** [comment]
@dilipprasad can this issue be closed?

**Comment by Schattenruf** [comment]
Hi,

have the same issue here.
My phone says "Streaming with active wakelock" but on my pi nothing happens. IP & User are correct and I have downloaded omxplayer and followed the instructions here.

(I was on a non gui raspbian before. Now I downloaded the gui because I thought this was the problem).

**Comment by nagualcode** [comment]
can you point me the link to where it says omxiv is a casting/streaming solution?

**Comment by Schattenruf** [comment]
Well it is if you use it with Raspicast. I have tested it with a new Clean
Installation of Raspbian Buster and that works just fine.

nagualcode <notifications@github.com> schrieb am Mo., 25. Nov. 2019, 21:11:

**Comment by nagualcode** [comment]
Well, "Raspicast" is the casting/streaming software.
Omxiv may be just a dependency, Raspicast needs to work. But in fact, Omxiv is just a photo (jpg/png files) viewer for the raspberry, not even a video player.
So this casting issue is not related to Omxiv at all.

**Comment by Ruffio** [comment]
Please close this.
