### ISSUE TITLE
Blend animation - unable to get it working

### ISSUE THREAD

**Issue by colloqi** [HaarigerHarald/omxiv#5]
Thanks for the excellent code! I am unable to get the animation working on Pi 3. Is there a configuration I am missing in config.txt? 
command - omxiv -t 5 -T blend --duration 1200 *.jpg
everything works except alpha is always 255 (irrespective of any value given under testing)

Thanks once again.

**Comment by colloqi** [comment]
I could get it working after changing the resize colorformat to OMX_COLOR_FormatYUV420PackedPlanar 

Thanks

**Comment by nagualcode** [comment]
where did you made that change?

**Comment by colloqi** [comment]
<img width="1126" alt="screen shot 2018-07-25 at 10 23 44 am" src="https://user-images.githubusercontent.com/1736279/43180294-e1a94cfa-8ff4-11e8-9048-e1a105ca125b.png">

**Comment by nagualcode** [comment]
Thank you.
It worked.
I sent a pull request here.

**Comment by HaarigerHarald** [comment]
Hi,

the problem with this workaround is that you will lose pixel data for everything other than normal jpegs. When I wrote the part with the blend transition the argb alpha channel was ignored but display config alpha was respected, now it's the other way around, which imho isn't correct either. A proper fix therefor would require some firmware change. The best workaround I guess would be to render in the same format as the decoded image

**Comment by nagualcode** [comment]
How can I make omxiv quits after one iteiration over the imagefiles in dir?
