### ISSUE TITLE
netflix

### ISSUE THREAD

**Issue by roboso** [HaarigerHarald/omxiv#6]
it would be a great thing, if you could even sharare netflix cb01 and prime-video

**Comment by Ruffio** [comment]
This should be closed if it is never going to be implemented...

**Comment by cemox35** [comment]
Netflix and spotify should be added if it is possible.

**Comment by Ruffio** [comment]
This request should be closed as it is out side the scope of the project. According to the readme the (https://github.com/HaarigerHarald/omxiv/blob/master/README.md) project is only about displaying images. How does Netflix come into that category?

Please close this request as out of scope.

**Comment by HaarigerHarald** [comment]
I agree, as this is an image viewing program it is definitly out of scope.
